server {
    listen 80;
    server_name apps;

    return 301 https://apps.pa-tools.work$request_uri;
}

server {
    listen 443 ssl http2;
    server_name apps.pa-tools.work;

    ssl_certificate /etc/letsencrypt/live/pa-tools.work/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pa-tools.work/privkey.pem;
    include snippets/splapps-ssl.conf;

    # Static files and API
    location / {
        proxy_pass http://127.0.0.1:3100;
        include snippets/splapps-proxy.conf;
    }
}